/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ExperiencesRouteImport } from './routes/experiences'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ClaimAdminRouteImport } from './routes/claim-admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExperiencesSlugRouteImport } from './routes/experiences.$slug'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as AuthenticatedMyBookingsRouteImport } from './routes/_authenticated/my-bookings'
import { Route as AuthenticatedCheckoutRouteImport } from './routes/_authenticated/checkout'
import { Route as AuthenticatedCartRouteImport } from './routes/_authenticated/cart'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedBookingSuccessIdRouteImport } from './routes/_authenticated/booking-success.$id'
import { Route as AuthenticatedBookIdRouteImport } from './routes/_authenticated/book.$id'

const ExperiencesRoute = ExperiencesRouteImport.update({
  id: '/experiences',
  path: '/experiences',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaimAdminRoute = ClaimAdminRouteImport.update({
  id: '/claim-admin',
  path: '/claim-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperiencesSlugRoute = ExperiencesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ExperiencesRoute,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMyBookingsRoute = AuthenticatedMyBookingsRouteImport.update({
  id: '/my-bookings',
  path: '/my-bookings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCheckoutRoute = AuthenticatedCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCartRoute = AuthenticatedCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBookingSuccessIdRoute =
  AuthenticatedBookingSuccessIdRouteImport.update({
    id: '/booking-success/$id',
    path: '/booking-success/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBookIdRoute = AuthenticatedBookIdRouteImport.update({
  id: '/book/$id',
  path: '/book/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/claim-admin': typeof ClaimAdminRoute
  '/contact': typeof ContactRoute
  '/experiences': typeof ExperiencesRouteWithChildren
  '/admin': typeof AuthenticatedAdminRoute
  '/cart': typeof AuthenticatedCartRoute
  '/checkout': typeof AuthenticatedCheckoutRoute
  '/my-bookings': typeof AuthenticatedMyBookingsRoute
  '/category/$slug': typeof CategorySlugRoute
  '/experiences/$slug': typeof ExperiencesSlugRoute
  '/book/$id': typeof AuthenticatedBookIdRoute
  '/booking-success/$id': typeof AuthenticatedBookingSuccessIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/claim-admin': typeof ClaimAdminRoute
  '/contact': typeof ContactRoute
  '/experiences': typeof ExperiencesRouteWithChildren
  '/admin': typeof AuthenticatedAdminRoute
  '/cart': typeof AuthenticatedCartRoute
  '/checkout': typeof AuthenticatedCheckoutRoute
  '/my-bookings': typeof AuthenticatedMyBookingsRoute
  '/category/$slug': typeof CategorySlugRoute
  '/experiences/$slug': typeof ExperiencesSlugRoute
  '/book/$id': typeof AuthenticatedBookIdRoute
  '/booking-success/$id': typeof AuthenticatedBookingSuccessIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/claim-admin': typeof ClaimAdminRoute
  '/contact': typeof ContactRoute
  '/experiences': typeof ExperiencesRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/cart': typeof AuthenticatedCartRoute
  '/_authenticated/checkout': typeof AuthenticatedCheckoutRoute
  '/_authenticated/my-bookings': typeof AuthenticatedMyBookingsRoute
  '/category/$slug': typeof CategorySlugRoute
  '/experiences/$slug': typeof ExperiencesSlugRoute
  '/_authenticated/book/$id': typeof AuthenticatedBookIdRoute
  '/_authenticated/booking-success/$id': typeof AuthenticatedBookingSuccessIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/claim-admin'
    | '/contact'
    | '/experiences'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/my-bookings'
    | '/category/$slug'
    | '/experiences/$slug'
    | '/book/$id'
    | '/booking-success/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/claim-admin'
    | '/contact'
    | '/experiences'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/my-bookings'
    | '/category/$slug'
    | '/experiences/$slug'
    | '/book/$id'
    | '/booking-success/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/claim-admin'
    | '/contact'
    | '/experiences'
    | '/_authenticated/admin'
    | '/_authenticated/cart'
    | '/_authenticated/checkout'
    | '/_authenticated/my-bookings'
    | '/category/$slug'
    | '/experiences/$slug'
    | '/_authenticated/book/$id'
    | '/_authenticated/booking-success/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ClaimAdminRoute: typeof ClaimAdminRoute
  ContactRoute: typeof ContactRoute
  ExperiencesRoute: typeof ExperiencesRouteWithChildren
  CategorySlugRoute: typeof CategorySlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/experiences': {
      id: '/experiences'
      path: '/experiences'
      fullPath: '/experiences'
      preLoaderRoute: typeof ExperiencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claim-admin': {
      id: '/claim-admin'
      path: '/claim-admin'
      fullPath: '/claim-admin'
      preLoaderRoute: typeof ClaimAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiences/$slug': {
      id: '/experiences/$slug'
      path: '/$slug'
      fullPath: '/experiences/$slug'
      preLoaderRoute: typeof ExperiencesSlugRouteImport
      parentRoute: typeof ExperiencesRoute
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/my-bookings': {
      id: '/_authenticated/my-bookings'
      path: '/my-bookings'
      fullPath: '/my-bookings'
      preLoaderRoute: typeof AuthenticatedMyBookingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/checkout': {
      id: '/_authenticated/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof AuthenticatedCheckoutRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cart': {
      id: '/_authenticated/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof AuthenticatedCartRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/booking-success/$id': {
      id: '/_authenticated/booking-success/$id'
      path: '/booking-success/$id'
      fullPath: '/booking-success/$id'
      preLoaderRoute: typeof AuthenticatedBookingSuccessIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/book/$id': {
      id: '/_authenticated/book/$id'
      path: '/book/$id'
      fullPath: '/book/$id'
      preLoaderRoute: typeof AuthenticatedBookIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedCartRoute: typeof AuthenticatedCartRoute
  AuthenticatedCheckoutRoute: typeof AuthenticatedCheckoutRoute
  AuthenticatedMyBookingsRoute: typeof AuthenticatedMyBookingsRoute
  AuthenticatedBookIdRoute: typeof AuthenticatedBookIdRoute
  AuthenticatedBookingSuccessIdRoute: typeof AuthenticatedBookingSuccessIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedCartRoute: AuthenticatedCartRoute,
  AuthenticatedCheckoutRoute: AuthenticatedCheckoutRoute,
  AuthenticatedMyBookingsRoute: AuthenticatedMyBookingsRoute,
  AuthenticatedBookIdRoute: AuthenticatedBookIdRoute,
  AuthenticatedBookingSuccessIdRoute: AuthenticatedBookingSuccessIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ExperiencesRouteChildren {
  ExperiencesSlugRoute: typeof ExperiencesSlugRoute
}

const ExperiencesRouteChildren: ExperiencesRouteChildren = {
  ExperiencesSlugRoute: ExperiencesSlugRoute,
}

const ExperiencesRouteWithChildren = ExperiencesRoute._addFileChildren(
  ExperiencesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ClaimAdminRoute: ClaimAdminRoute,
  ContactRoute: ContactRoute,
  ExperiencesRoute: ExperiencesRouteWithChildren,
  CategorySlugRoute: CategorySlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
